#!/bin/sh

VERSION="1.1.1"

echo "prepare for distribution"

real_run=$1

git checkout -b dist${VERSION}

cp .gitignore-dist .gitignore

grunt build


if [ "$real_run" = "run" ]; then
    echo bmp -c
    bmp -c
    echo npm publish
    npm publish
else
    echo "  $0 \"run\" will publish in npm and push git tag.
        Instead, do the following commands.

        bmp -c
        npm publish
        "

fi
