###
generated by base-domain generator
###


Entity = require('base-domain').Entity


class <%=@Model%> extends Entity

    @properties:
    ### examples
        name      : @TYPES.STRING
        age       : @TYPES.NUMBER
        confirmed : @TYPES.BOOLEAN
        createdAt : @TYPES.DATE
        team      : @TYPES.MODEL 'team'
        hobbies   : @TYPES.MODELS 'hobby'
    ###

module.exports = <%=@Model %>
