###
generated by base-domain generator
###


BaseFactory = require('base-domain').BaseFactory


###*
factory of <%= @model  %>


@class <%= @Model %>Factory
@extends BaseFactory
###
class <%=@Model %>Factory extends BaseFactory

    ###*
    model name to create

    @property modelName
    @static
    @protected
    @type String
    ###
    @modelName: '<%= @model %>'

module.exports = <%=@Model %>Factory
