###
generated by base-domain generator
###


BaseRepository = require('base-domain').BaseRepository


class <%=@Model %>Repository extends BaseRepository

    @modelName: '<%=@model %>'

module.exports = <%=@Model %>Repository
