###
generated by base-domain generator
###


BaseRepository = require('../base-domain').BaseRepository

###*
repository of diary

@class DiaryRepository
@extends BaseRepository
###
class DiaryRepository extends BaseRepository

    ###*
    model name to create

    @property modelName
    @static
    @protected
    @type String
    ###
    @modelName: 'diary'

module.exports = DiaryRepository
