###
generated by base-domain generator
###


BaseFactory = require('../base-domain').BaseFactory


###*
factory of diary

@class DiaryFactory
@extends BaseFactory
###
class DiaryFactory extends BaseFactory

    ###*
    model name to create

    @property modelName
    @static
    @protected
    @type String
    ###
    @modelName: 'diary'

module.exports = DiaryFactory
