###
generated by base-domain generator
###


BaseRepository = require('../base-domain').BaseRepository

###*
repository of member

@class MemberRepository
@extends BaseRepository
###
class MemberRepository extends BaseRepository

    ###*
    model name to create

    @property modelName
    @static
    @protected
    @type String
    ###
    @modelName: 'member'

module.exports = MemberRepository
